name: rxnet_plus
description: Based on Dio's extended network request framework, it supports various caching strategies and is easy to use
version: 0.5.0
homepage: https://github.com/zhengzaihong/rxnet

platforms:
  windows:
  web:
  android:
  linux:
  ios:
  macos:


environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=2.18.0"

dependencies:
  flutter:
    sdk: flutter

  crypto:  ^3.0.2
  dio: ^5.8.0+1
  hive: ^2.2.3
  path: ^1.9.0
  path_provider: ^2.1.5
  path_provider_platform_interface: ^2.1.0
dev_dependencies:
  flutter_lints: ^2.0.0



flutter:
  plugin:
    platforms:
      implements: path_provider
      some_platform:
        pluginClass: somePluginClass
      ohos:
        pluginClass: RxNetPathProviderPlugin
        dartPluginClass: RxNetPlus

